services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=users
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DSN=host=postgres user=root password=secret dbname=users port=5432 sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432","--"]
    command: ["/app/main"]
